### ISSUE TITLE
Drag and drop does not work

### ISSUE THREAD

**Issue by SaadiSave** [flathub/com.belmoussaoui.Obfuscate#8]
Just the title

**Comment by bilelmoussaoui** [comment]
Not an app issue, the source app should be using gtk4 as well.

**Comment by SaadiSave** [comment]
Isn't that rather restrictive (I would even argue that it makes drag and drop useless), given that Nautilus is still a GTK3 app and other file managers aren't even GTK? Could you please point me to a resource that explains why this restriction exists? Is this a problem with GTK 4 or obfuscate?
